 # make sure the action works on a clean machine without building
name: prod

on:
  pull_request:
  push:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Test wrapper
      uses: ./
      with:
        wrapper-directory: __tests__/data/basic
        build-root-directory: __tests__/data/basic
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: test
    - name: Test dist download
      uses: ./
      with:
        gradle-version: rc
        build-root-directory: __tests__/data/basic
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: test --configuration-cache
    - name: Test dependency resolution dump
      uses: ./
      with:
        gradle-version: rc
        build-root-directory: __tests__/data/library
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        export-resolved-dependencies: true
        arguments: test
    - name: Stop Gradle daemon
      uses: ./
      with:
        gradle-version: rc
        build-root-directory: __tests__/data/basic
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
        arguments: --stop
